#!/bin/bash
#=================================================
# File name: init-settings.sh
# System Required: Linux
# Version: 1.0
# Lisence: MIT
# Author: SuLingGG
# Blog: https://mlapp.cn
#=================================================
# 设置默认主题 luci-theme-argon
uci set luci.main.mediaurlbase='/luci-static/argon'

# 停止 sing-box
/etc/init.d/sing-box stop
/etc/init.d/sing-box disable

# 禁用 uhttpd
# /etc/init.d/uhttpd stop
# /etc/init.d/uhttpd disable

# 替换 Nginx 配置文件 nginx
if [ -e package/base-files/files/etc/config/nginx ]; then
    rm -rf package/base-files/files/etc/config/nginx
fi
mv package/base-files/files/etc/config/nginx.tmp package/base-files/files/etc/config/nginx
# 替换 Nginx 配置文件 nginx.conf
if [ -e package/base-files/files/etc/nginx/nginx.conf ]; then
    rm -rf package/base-files/files/etc/nginx/nginx.conf
fi
mv package/base-files/files/etc/nginx/nginx.conf.tmp package/base-files/files/etc/nginx/nginx.conf
# 替换 uwsgi 配置文件 luci-cgi_io.ini
if [ -e package/base-files/files/etc/uwsgi/vassals/luci-cgi_io.ini ]; then
    rm -rf package/base-files/files/etc/uwsgi/vassals/luci-cgi_io.ini
fi
mv package/base-files/files/etc/uwsgi/vassals/luci-cgi_io.ini.tmp package/base-files/files/etc/uwsgi/vassals/luci-cgi_io.ini
# 重启 Nginx
/etc/init.d/nginx restart

# 禁用 opkg 签名检查
sed -i 's/option check_signature/# option check_signature/g' /etc/opkg.conf

# 禁用 IPV6 前缀
sed -i 's/^[^#].*option ula/#&/' /etc/config/network

# 禁用某些软件包的自启
cd /etc/rc.d
rm -f S98udptools || true
rm -f S99nft-qos || true

# Try to execute init.sh (if exists)

if [ ! -f "/boot/init.sh" ]; then
bash /boot/init.sh
fi

exit 0
