#!/bin/bash
#=================================================
# File name: init-settings.sh
# System Required: Linux
# Version: 1.0
# Lisence: MIT
# Author: SuLingGG
# Blog: https://mlapp.cn
#=================================================
# 设置默认主题 luci-theme-argon
uci set luci.main.mediaurlbase='/luci-static/argon'

# 停止 sing-box
/etc/init.d/sing-box stop
/etc/init.d/sing-box disable

# 禁用 uhttpd
# /etc/init.d/uhttpd stop
# /etc/init.d/uhttpd disable

# 禁用 opkg 签名检查
sed -i 's/option check_signature/# option check_signature/g' /etc/opkg.conf

# 禁用 IPV6 前缀
# sed -i 's/^[^#].*option ula/#&/' /etc/config/network

# 禁用某些软件包的自启
cd /etc/rc.d
rm -f S98udptools || true
rm -f S99nft-qos || true

# Try to execute init.sh (if exists)

if [ ! -f "/boot/init.sh" ]; then
bash /boot/init.sh
fi

exit 0
